### ISSUE TITLE
RCS не работает

### ISSUE THREAD

**Issue by Pidermen** [blyatArtem/cs2#10]
Я хуй знает почему, но я включаю функцию, а самого контроля я не чуствую, такая же отдача и нечего более.

**Comment by blyatArtem** [comment]
похуй. Я с аимом не играю.

**Comment by blyatArtem** [comment]
У меня если что вс работает, а хуже стало скорее всего из-за новых настроек. Их можно на минимум поставить, но жрать много будет прога

**Comment by Pidermen** [comment]
хз, я забилдил все окей, но аимбот не робит, юзал кейбинд и менял даже, все равно проблема

**Comment by Pidermen** [comment]
ОТМЕНА!!! Аимбот и триггербот робит, поменял бинд и все оке
