### ISSUE TITLE
Баг с отображением

### ISSUE THREAD

**Issue by MAX1MDEV** [blyatArtem/cs2#4]
Вместо того, чтобы отображение было нормальным, оно отображает снизу от персонажа. В чем может быть проблема?

**Comment by blyatArtem** [comment]
Привет. Возможно проблема в  [графическом оверлее](https://github.com/michel-pi/GameOverlay.Net).
Подобные проблемы возникают если у Вас несколько мониторов. Так же может быть проблема в работе с мартицой.

**Comment by MAX1MDEV** [comment]
Вроде проблем нет, проверил в другом external чите, все нормально. У тебя поприятнее дизайн и легитнее как никак, вот и хочу, чтобы заработало как надо. Готов к любым костылям если есть идеи)

**Comment by blyatArtem** [comment]
https://vk.com/hellocsharp
пиши в вк. ща глянем

**Comment by blyatArtem** [comment]
Решение: Нужно изменить в настройках System > Display > Scaling на 100%
