### ISSUE TITLE
No menu- When I press HOME, I get a black screen with no menu. 

### ISSUE THREAD

**Issue by Kawaiuwu69** [blyatArtem/cs2#5]
When i compile, any method of compiling I press HOME, i get no menu, only a more ''black'' screen.

When I download release I get ''memory... error'' 

So... Either my portable is dog sht and i should try on my pc.. or source got problems ? :o HELP PLEASE LOVE U ALL UWU 69

**Comment by blyatArtem** [comment]
"Memory init failed" means Cs2 procces not found. Also mb current (cheat) procces already exists.

**Comment by blyatArtem** [comment]
"Memory init failed" displays then csgo process not found.

**Comment by Kawaiuwu69** [comment]
I don't know why you close it... Cs2 was open, it's just doesn't attach to it and says memory init or wtv.
Also, when I do compile it myself I get the menu etc on my main pc. On my laptop nothing but a black screen. Even if the ''menu loads'' the esp etc, when in a game don't appear... 
Do I need to update offsets or something or I'm just not able to make it work ?
Also how do you compile ''AOT native'' i have no idea how to do that even after looking ytb videos ;-; . S.O.S
