### ISSUE TITLE
Still error when im in game

### ISSUE THREAD

**Issue by Dino-log** [blyatArtem/cs2#7]
![image](https://github.com/blyatArtem/cs2/assets/66836260/2236a59e-5548-4e51-9006-30591a1a46b9)

**Comment by blyatArtem** [comment]
1. The program is already running
https://github.com/blyatArtem/cs2/blob/da96caa9e15b95f91bbcfaef8c901c52af6ba181/cs2/Memory.cs#L19
2. The game process was not found BY NAME
https://github.com/blyatArtem/cs2/blob/da96caa9e15b95f91bbcfaef8c901c52af6ba181/cs2/Memory.cs#L22
