### ISSUE TITLE
render, game process found, cpu issue 

### ISSUE THREAD

**Issue by sergeyutkin1** [blyatArtem/cs2#8]
![Screenshot_1](https://github.com/blyatArtem/cs2/assets/161523571/7495b66c-fb00-47ec-994f-e9aa3080b510)
![Screenshot_2](https://github.com/blyatArtem/cs2/assets/161523571/622456d8-9838-4391-8f64-fd63f538ae44)
![Screenshot_3](https://github.com/blyatArtem/cs2/assets/161523571/d0909f38-e367-49f9-82c3-ec9c50d8b682)

**Comment by blyatArtem** [comment]
fix:
![image](https://github.com/blyatArtem/cs2/assets/91653434/64391ac7-7522-45ce-b7c7-892adcb54d2a)

**Comment by sergeyutkin1** [comment]
I originally had 100 % screen scale -_-
![image](https://github.com/blyatArtem/cs2/assets/161523571/f0836775-ff7d-4eb8-ae1f-e564a9f71651)

**Comment by sergeyutkin1** [comment]
fuck dude now I see why the сpu issue, what's your problem using a dictionary?

https://github.com/blyatArtem/cs2/blob/da96caa9e15b95f91bbcfaef8c901c52af6ba181/cs2/Game/Objects/Weapon.cs#L46

**Comment by blyatArtem** [comment]
Привет. Я предпочитаю говорить по-русский :)
Не сразу разобрался в твоем вопросе, постараюсь дать полный ответ.

1. "game process found".

Я попробовал запустить версию программы, которую я выложил как "release" и она вывела исключение "Memory init failed". Скорее всего вечером починю.
Уточнение: Я в кс2 не играю и написание чита это как простенькая задачка, которую я делал в свободное время. Опять же я вообще не играю и в следствии не тестировал. Каюсь!

НО!!! Если скомпилировать проект самостоятельно, то всё работает безупречно. Попробуй сам. Ошибок никаких нету.

![image](https://github.com/blyatArtem/cs2/assets/91653434/a9b54b65-7866-499c-9c83-cf56ba699a52)

2. "cpu issue"

![image](https://github.com/blyatArtem/cs2/assets/91653434/05215d08-be9c-4c07-9300-ef333ef1d35b)
![image](https://github.com/blyatArtem/cs2/assets/91653434/de05f685-3b58-4023-966f-5398ef0ec0c3)


В предыдущих скриншотах четко видно, что программа не требует сверх вычислений для компьютеров НАСА. Я бы хотел подробнее разобраться почему на Вашем компьютере очень сильная нагрузка на процессор, а на моем древнем ноутбуке, который еле-еле тянет кс2, всё работает как по маслу. Был бы рад если бы Вы помогли мне разобраться с этой проблемой. Из моих знакомых никто с подобным не сталкивался, но всё же у меня есть предположение:
Оверлей программы работает при помощи SharpDX (SharpDX - это проект с открытым исходным кодом, предоставляющий полный DirectX API для .Net на всех платформах Windows, позволяющий разрабатывать высокопроизводительные игры, рендеринг 2D и 3D-графики, а также звуковые приложения в реальном времени). Возможно обработка графики работает некорректно из-за старой версии DirectX или что-то не так с  аппаратным ускорением. Еще хочу напомнить, что DirectX плотно сидит в системе и взаимодействовать с ним не очень хочетсяю
3. "render"

Если Вы про первый Ваш скриншот, то скорее всего проблема связано с моим вторым ответом. Либо неправильно преобразуется матрица под ваше изображение.

4. "fuck dude now I see why the сpu issue, what's your problem using a dictionary?"

Прости, что не сэкономил тебе 2 лишние наносекунды.

5. "LMAO Brushes.cs" Я решил не работать над деструкторами и отчисткой т.к программа завершает свою работу после окончания работы потока оверлея. И вся аллоцированная память отчищается.  Но если Вы имеете в виду как я реализовал класс Brushes, то можем вместе декомпилировать System.Drawing.Colors и посмеяться над Microsoft.

В следующий раз пожалуйста будьте конкретнее.

**Comment by blyatArtem** [comment]
Уточка моя. Если есть еще какие-то вопросы, то лучше пиши мне в ВК. Я редко занимаюсь программированием и лишний раз в гитхаб не захожу. [Тык](https://vk.com/id481334475).

**Comment by sergeyutkin1** [comment]
> В предыдущих скриншотах четко видно, что программа не требует сверх вычислений для компьютеров НАСА

requires if the included functionality is going to be more than ESP and Skeleton. 
because if you get here.
https://github.com/blyatArtem/cs2/blob/da96caa9e15b95f91bbcfaef8c901c52af6ba181/cs2/Game/Features/AimAssist.cs#L56
https://github.com/blyatArtem/cs2/blob/da96caa9e15b95f91bbcfaef8c901c52af6ba181/cs2/Game/Features/Bhop.cs#L20
it all makes sense why the cpu issue 



> неправильно преобразуется матрица под ваше изображение.

because https://github.com/blyatArtem/cs2/blob/da96caa9e15b95f91bbcfaef8c901c52af6ba181/cs2/Game/Objects/LocalPlayer.cs#L44
https://github.com/blyatArtem/cs2/blob/da96caa9e15b95f91bbcfaef8c901c52af6ba181/cs2/GameOverlay/Overlay.cs#L37

> Прости, что не сэкономил тебе 2 лишние наносекунды.

>  Я решил не работать над деструкторами и отчисткой т.к программа завершает свою работу после окончания работы потока оверлея.

if you remove this yandere dev code, this is what the load will be, on the same cfg 
![Screenshot_1](https://github.com/blyatArtem/cs2/assets/161523571/3b208dd1-79f7-4f87-aaf0-1d0d3ae82bc6)

I think you have some work to do.

**Comment by blyatArtem** [comment]
I'm really grateful to you <3. Even if it's a fun project. I will try to improve.
Initially, the project was created only for me and a friend. I forgot to remove the screen size constants.

И еще у тебя вроде как скриншоты на русском. Ник твой тоже русский. Я особо не планирую помогать англоговорящим и ты мог не стараться с переводом :p

**Comment by blyatArtem** [comment]
Кстати, у меня реально камушек слабый, но я не замечал проблемы с нагрузкой процессора 
![image](https://github.com/blyatArtem/cs2/assets/91653434/3854f836-385c-4171-9c2e-abcce3451a66)
