### ISSUE TITLE
uwu anime weeburl ara ara

### ISSUE THREAD

**Issue by Kawaiuwu69** [blyatArtem/cs2#9]
I don't know how to make it work ;-; I compile etc. Follow each step... can you help me please ? or a new released version perhaps por favor ^^ 

uwu. GG wp

**Comment by blyatArtem** [comment]
1.
![Screenshot 2024-03-20 153019](https://github.com/blyatArtem/cs2/assets/91653434/ad153e61-0c4e-4205-a83d-6dc4664a7fdc)
2.
![Screenshot 2024-03-20 153027](https://github.com/blyatArtem/cs2/assets/91653434/a1cfb0a0-1fcb-4315-a9cb-974c16b4e980)
3.
![Screenshot 2024-03-20 153048](https://github.com/blyatArtem/cs2/assets/91653434/7c1f9ece-1ff2-4250-92dd-c02a3021a308)
4.
![Screenshot 2024-03-20 153246](https://github.com/blyatArtem/cs2/assets/91653434/824ff67a-5a8e-4717-a3fc-9c916b5954f6)

**Comment by Kawaiuwu69** [comment]
Thank you I will try that and let u know :p Loveu
